CREATE TABLE channels
(
    id         VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_channels PRIMARY KEY (id)
);

CREATE TABLE sources
(
    id         VARCHAR(64)                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_sources PRIMARY KEY (id)
);

CREATE TABLE subscriptions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_id VARCHAR(255)                            NOT NULL,
    source_id  VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);

ALTER TABLE subscriptions
    ADD CONSTRAINT uc_subscriptions_channel UNIQUE (channel_id);

ALTER TABLE subscriptions
    ADD CONSTRAINT uc_subscriptions_source UNIQUE (source_id);

CREATE UNIQUE INDEX idx_channel_id_source ON subscriptions (channel_id, source_id);

ALTER TABLE subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (id);

ALTER TABLE subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_SOURCE FOREIGN KEY (source_id) REFERENCES sources (id);